### ISSUE TITLE
超分导致游戏崩溃 v0.4.1

### ISSUE THREAD

**Issue by pb8DvwQkfRR** [ChanIok/SpinningMomo#1]
显示器原生分辨率3840*2160，游戏使用全屏窗口模式
比例调节功能正常，超分的话会导致游戏直接崩溃，表现窗口会溢出屏幕，然后卡住。几秒后弹出崩溃提示。
尝试过游戏画面调至最低配置同样崩溃，显存也没有满的痕迹。也没找到这游戏崩溃日志跑哪里去了。。
![image](https://github.com/user-attachments/assets/94be731f-592e-44e0-a185-9eb25d615478)

**Comment by ChanIok** [comment]
尝试使用稍微低一些的分辨率，例如5000x3000？
大分辨率很吃内存，此前我和群友试过12k都是可以的，但就是很卡。我的配置不算高，如果设置更大分辨率，也是会卡死崩溃。

**Comment by ChanIok** [comment]
找到原因了，代码没考虑缩放率的情况，如果Windows设置了缩放率，例如200%，那么8k就实际被设置成了16k。
该问题已经在[0.4.2版本](https://github.com/your-repo/releases/tag/v0.4.2)修复，请再试下。

**Comment by pb8DvwQkfRR** [comment]
晚些我会尝试，谢谢。
另外我使用 v0.4.1 版本发现在【全屏窗口模式】下，只有 16:9 和 9:16 比例能够正确输出相应尺寸的照片（分别为3840*2160和2160*3840）。其它比例如1:1、3:2、21:9等，实际输出的图片都会变成3840*2160，在大喵相册中显示的也是这个尺寸。要想正确保存这些自定义比例的照片，需要切换到【窗口模式】才行。
您在使用过程中有遇到吗？不知道是否和 DPI 感知有关系。

**Comment by ChanIok** [comment]
这个情况是正常的，我推测跟游戏本身【拍照画质】的设置以及它照片生成的逻辑有关，根据我的测试情况：
【全屏窗口模式】如果想输出其它不同比例（除了屏幕本身比例和它的翻转）的照片，【拍照画质】只能选择【窗口分辨率】，但是那样输出的尺寸肯定是基于屏幕的尺寸进行裁剪了。
【窗口模式】却没有以上这个限制，只是它不能设置超过屏幕尺寸的大小。

**Comment by pb8DvwQkfRR** [comment]
确认问题已在 v0.4.2 修复。
